---
abstract: 'Object approach at reading explain analyze output'
author:
  - 'scott kahler <scott.kahler@gmail.com>'
build_requires:
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0
  autodie: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GP-Explain
provides:
  GP::Explain:
    file: lib/GP/Explain.pm
    version: 0.03
  GP::Explain::From:
    file: lib/GP/Explain/From.pm
    version: 0.03
  GP::Explain::FromText:
    file: lib/GP/Explain/FromText.pm
    version: 0.03
  GP::Explain::Node:
    file: lib/GP/Explain/Node.pm
    version: 0.03
  GP::Explain::StringAnonymizer:
    file: lib/GP/Explain/StringAnonymizer.pm
    version: 0.03
requires:
  Clone: 0
  Digest::SHA1: 0
  HOP::Lexer: 0
  perl: 5.010
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
